### ISSUE TITLE
Issue on docker swarm setup

### ISSUE THREAD

**Issue by gitzec** [jammsen/docker-sons-of-the-forest-dedicated-server#25]
### Have you read the Important information text above

- [X] Yes i did

### Current behavior

Hi, as the title states I am not able to get this up and running.

I am running a 4 node docker swarm here and also a lot of services in it.

For SOTF i added this to my stack:
```yaml
  sotf: # Sons of the Forest Server
    image: jammsen/sons-of-the-forest-dedicated-server:latest
    environment:
      ALWAYS_UPDATE_ON_START: 1
    ports:
      - "8766:8766/udp"
      - "27016:27016/udp"
      - "9700:9700/udp"
    volumes:
      - /media/docker/darknet_sotf/steamcmd/:/steamcmd
      - /media/docker/darknet_sotf/sonsoftheforest/:/sonsoftheforest
      - /media/docker/darknet_sotf/winedata/:/winedata
    deploy:
      placement:
        preferences:
          - spread: node.labels.Focus == power
    networks:
      - docker-darknet
```

When the container starts up it creates files and folders inside the three volumes (which are hosted from a QTS NAS via nfs, exports are mounted on each docker node of the swarm).

Tree looks like this:
```
.
├── sonsoftheforest
│   ├── steam_appid.txt
│   └── userdata
│       ├── dedicatedserver.cfg
│       └── ownerswhitelist.txt
├── steamcmd
│   ├── linux32
│   │   ├── libstdc++.so.6
│   │   └── steamcmd
│   ├── steamcmd.sh
│   └── steam.sh
└── winedata
    └── WINE64
        ├── dosdevices
        │   ├── c: -> ../drive_c
        │   └── z: -> /
        ├── drive_c
        │   ├── ProgramData
        │   │   └── Microsoft
        │   │       └── Windows
        │   │           ├── Start Menu
        │   │           │   └── Programs
        │   │           │       ├── Administrative Tools
        │   │           │       └── StartUp
        │   │           └── Templates
        │   ├── Program Files
        │   │   ├── Common Files
...
```

But, the server never comes up. The container dies and a new one is spawned all the time. The last log I saw shows this:
```
>>> Doing a fresh install of the gameserver
>>> Checking if Wine is set in bashrc
>>> Setting up Wine in bashrc
/steamcmd/steamcmd.sh: line 29: /steamcmd/linux32/steamcmd: Permission denied
>>> Doing an update of the gameserver
/steamcmd/steamcmd.sh: line 29: /steamcmd/linux32/steamcmd: Permission denied
0024:err:virtual:map_file_into_view failed to set PROT_EXEC on file map, noexec filesystem?
0024:err:virtual:virtual_map_section mapping 0x250000 17000 0 failed
00d8:err:virtual:map_file_into_view failed to set PROT_EXEC on file map, noexec filesystem?
00d8:err:virtual:virtual_map_section mapping 0x250000 17000 0 failed
>>> Starting the gameserver
wine: failed to open "/sonsoftheforest/SonsOfTheForestDS.exe": c0000135
```
I did a `chmod 777 /steamcmd/linux32/steamcmd` even though it was +x for root anyway but that did not solve the issue.

### Desired behavior

Container starts up and the SOTF server is being visible in the game client.

### To Reproduce

See above.

### Software setup

- OS: Ubuntu Server 22.04 LTS + ESM (Docker Host)
- Docker:  24.0.5, build ced0996

### Hardware setup

- vCPU: 8
- RAM: 16
- Disk: 8T

### Additional context

Thanks for baking, publishing and even supporting this image.
