### ISSUE TITLE
SteamCMD can't load gameserver files

### ISSUE THREAD

**Issue by elec2** [jammsen/docker-sons-of-the-forest-dedicated-server#42]
### Have you read the Important information text above

- [X] Yes i did

### Current behavior

On startup with the following docker-compose

```
version: '3.9'
services:
  sons-of-the-forest:
    container_name: sons-of-the-forest
    image: jammsen/sons-of-the-forest-dedicated-server:latest
    restart: unless-stopped
    environment:
      ALWAYS_UPDATE_ON_START: 1

    ports:
      - 8766:8766/udp
      - 27016:27016/udp
      - 9700:9700/udp
    volumes:
      - /docker/sondoftheforest/steamcmd:/steamcmd
      - /docker/sondoftheforest/game:/sonsoftheforest
      - /docker/sondoftheforest/winedata:/winedata
```

the logview is showing the following:

```
>>> Starting the gameserver
wine: failed to open "/sonsoftheforest/SonsOfTheForestDS.exe": c0000135
>>> Doing a fresh install of the gameserver
tid(17) burning pthread_key_t == 0 so we never use it
WARNING: setlocale('en_US.UTF-8') failed, using locale: 'C'. International characters may not work.
Redirecting stderr to '/root/Steam/logs/stderr.txt'
Logging directory: '/root/Steam/logs'
[  0%] Checking for available updates...
[----] Verifying installation...
Steam Console Client (c) Valve Corporation - version 1708986792
-- type 'quit' to exit --
Loading Steam API...OK
@sSteamCmdForcePlatformType windows
"@sSteamCmdForcePlatformType" = "windows"
force_install_dir /sonsoftheforest
Connecting anonymously to Steam Public...OK
Waiting for client config...OK
Waiting for user info...OK
app_update 2465200 validate
 Update state (0x0) : Timed out waiting for update to start, bailing.
Error! App '2465200' state is 0x202 after update job.
quit
>>> Doing an update of the gameserver
tid(41) burning pthread_key_t == 0 so we never use it
WARNING: setlocale('en_US.UTF-8') failed, using locale: 'C'. International characters may not work.
Redirecting stderr to '/root/Steam/logs/stderr.txt'
Logging directory: '/root/Steam/logs'
[  0%] Checking for available updates...
[----] Verifying installation...
Steam Console Client (c) Valve Corporation - version 1708986792
-- type 'quit' to exit --
Loading Steam API...      ,>>> Doing a fresh install of the gameserver
tid(15) burning pthread_key_t == 0 so we never use it
[...]
```

### Desired behavior

SteamCMD should load gameserver files without timeout and the gameserver should start after installation.

### To Reproduce

1. Run image with my docker-compose
2. view logs

### Software setup

- OS: linux x86_64 Alpine Linux v3.17
- Docker: Standalone 20.10.24

### Hardware setup

- vCPU: 4  i5-1145G7 @ 2.60GHz
- RAM: 10GB
- Disk: 10GB

### Additional context

The vhost has full internet access.
