### ISSUE TITLE
Unable to download or start server

### ISSUE THREAD

**Issue by G-Dolan** [jammsen/docker-sons-of-the-forest-dedicated-server#57]
### Have you read the Important information text above

- [X] Yes i did

### Current behavior

Unable to start dedicated server.

```
ubuntu@spiderhoos:~/sotf$ docker-compose up
Starting sotf-server ... done
Attaching to sotf-server
sotf-server    | >>> Doing a fresh install of the gameserver
sotf-server    | WARNING: setlocale('en_US.UTF-8') failed, using locale: 'C'. International characters may not work.
sotf-server    | Redirecting stderr to '/root/Steam/logs/stderr.txt'
sotf-server    | Logging directory: '/root/Steam/logs'
sotf-server    | [  0%] Checking for available updates...
sotf-server    | [----] Verifying installation...
sotf-server    | UpdateUI: skip show logoSteam Console Client (c) Valve Corporation - version 1726605427
sotf-server    | -- type 'quit' to exit --
sotf-server    | Loading Steam API...IPC function call IClientUtils::GetConnectedUniverse took too long: 51 msec
sotf-server    | IPC function call IClientUtils::GetIPCountry took too long: 43 msec
sotf-server    | OK
sotf-server    | @sSteamCmdForcePlatformType windows
sotf-server    | "@sSteamCmdForcePlatformType" = "windows"
sotf-server    | force_install_dir /sonsoftheforest
sotf-server    |
sotf-server    | Connecting anonymously to Steam Public...OK
sotf-server    | Waiting for client config...OK
sotf-server    | Waiting for user info...OK
sotf-server    | app_update 2465200 validate
sotf-server    | ERROR! Failed to install app '2465200' (Missing file permissions)
sotf-server    | quit
sotf-server    | >>> Doing an update of the gameserver
sotf-server    | WARNING: setlocale('en_US.UTF-8') failed, using locale: 'C'. International characters may not work.
sotf-server    | Redirecting stderr to '/root/Steam/logs/stderr.txt'
sotf-server    | Logging directory: '/root/Steam/logs'
sotf-server    | [  0%] Checking for available updates...
sotf-server    | [----] Verifying installation...
sotf-server    | UpdateUI: skip show logoSteam Console Client (c) Valve Corporation - version 1726605427
sotf-server    | -- type 'quit' to exit --
sotf-server    | Loading Steam API...IPC function call IClientUtils::GetConnectedUniverse took too long: 50 msec
sotf-server    | IPC function call IClientUtils::GetIPCountry took too long: 46 msec
sotf-server    | OK
sotf-server    | @sSteamCmdForcePlatformType windows
sotf-server    | "@sSteamCmdForcePlatformType" = "windows"
sotf-server    | force_install_dir /sonsoftheforest
sotf-server    |
sotf-server    | Connecting anonymously to Steam Public...OK
sotf-server    | Waiting for client config...OK
sotf-server    | Waiting for user info...OK
sotf-server    | app_update 2465200 validate
sotf-server    | ERROR! Failed to install app '2465200' (Missing file permissions)
```

my docker config is very basic; 

```
version: '3.9'
services:
  sotf-server:
    container_name: sotf-server
    image: jammsen/sons-of-the-forest-dedicated-server
    restart: always
    environment:
      ALWAYS_UPDATE_ON_START: 1
    ports:
      - 8766:8766/udp
      - 27017:27017/udp
      - 9700:9700/udp
    volumes:
      - /home/ubuntu/sotf/sonsoftheforest:/sonsoftheforest
      - /home/ubuntu/sotf/steamcmd:/steamcmd
      - /home/ubuntu/sotf/winedata:/winedata
```

### Desired behavior

Would like the server to run

### Software setup

- OS: Ubuntu 22
- Docker: 24.0.7

### Hardware setup

- vCPU: 12
- RAM: 48GB
- Disk: 200gb 

### Additional context

I'm just trying to get a basic server up and running before I start fiddled in earnest :)
